// src/app/dashboard/pages/detection-system/detection-system.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-detection-system",
  templateUrl: "./detection-system.component.html",
  styleUrls: ["./detection-system.component.css"],
})
export class DetectionSystemComponent {
  isMonitoring = false
  detectionActive = false
  currentDetection: any = null
  alertSent = false
  progressValue = 0

  startMonitoring(): void {
    this.isMonitoring = true
    this.detectionActive = true
    this.alertSent = false
    this.currentDetection = null
    this.progressValue = 0

    const interval = setInterval(() => {
      this.progressValue += 20
      if (this.progressValue >= 100) {
        clearInterval(interval)
      }
    }, 1000)

    // Simulate real-time detection
    setTimeout(() => {
      const detections = [
        { animal: "Tiger", confidence: 94, behavior: "Aggressive", threat: "High", location: "Sector 7" },
        { animal: "Elephant", confidence: 87, behavior: "Alert", threat: "Medium", location: "Highway KM 15" },
        { animal: "Leopard", confidence: 91, behavior: "Hunting", threat: "High", location: "Buffer Zone 2" },
        { animal: "Wild Boar", confidence: 78, behavior: "Territorial", threat: "Medium", location: "Trail 3" },
      ]

      const randomDetection = detections[Math.floor(Math.random() * detections.length)]
      this.currentDetection = randomDetection

      if (randomDetection.threat === "High") {
        setTimeout(() => {
          this.alertSent = true
        }, 2000)
      }

      this.isMonitoring = false // Stop monitoring after a detection
      this.progressValue = 100
    }, 5000)
  }

  stopMonitoring(): void {
    this.isMonitoring = false
    this.detectionActive = false
    this.currentDetection = null
    this.alertSent = false
    this.progressValue = 0
  }

  simulateAlert(): void {
    this.alertSent = true
    // Simulate SMS/Email notification
    setTimeout(() => {
      alert(
        "Emergency Alert Sent!\n\n📱 SMS sent to registered travelers\n📧 Email alert to Forest Rangers\n🚨 Nearby patrol units notified",
      )
    }, 1000)
  }

  getThreatColorClass(threat: string): string {
    return threat === "High" ? "border-red-500 bg-red-50" : "border-yellow-500 bg-yellow-50"
  }

  getThreatTextColorClass(threat: string): string {
    return threat === "High" ? "text-red-600" : "text-yellow-600"
  }

  getBadgeColor(threat: string): string {
    return threat === "High" ? "warn" : "accent"
  }
}

<div class="space-y-6">
  <div>
    <h1 class="text-3xl font-bold text-gray-900">Simulated Detection System</h1>
    <p class="text-gray-600 mt-2">Real-time wildlife audio monitoring and automatic alert system</p>
  </div>

  <!-- Detection Control Panel -->
  <mat-card>
    <mat-card-header>
      <mat-card-title class="flex items-center gap-2">
        <mat-icon class="h-5 w-5">radio</mat-icon>
        Audio Detection Control
      </mat-card-title>
      <mat-card-subtitle>Activate real-time wildlife sound detection and monitoring</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content class="space-y-4">
      <div class="flex items-center gap-4">
        <button mat-raised-button
          [color]="detectionActive ? 'primary' : 'accent'"
          (click)="startMonitoring()"
          [disabled]="detectionActive">
          {{ detectionActive ? 'Detection Active' : 'Start Detection' }}
          <mat-icon class="ml-2">{{ detectionActive ? 'mic' : 'mic_none' }}</mat-icon>
        </button>

        <button mat-raised-button color="warn" (click)="stopMonitoring()" [disabled]="!detectionActive">
          Stop Detection
          <mat-icon class="ml-2">mic_off</mat-icon>
        </button>

        <div class="flex items-center gap-2">
          <div class="w-3 h-3 rounded-full" [ngClass]="detectionActive ? 'bg-green-500 animate-pulse' : 'bg-gray-300'"></div>
          <span class="text-sm text-gray-600">{{ detectionActive ? 'Listening...' : 'Inactive' }}</span>
        </div>
      </div>

      <div *ngIf="isMonitoring" class="space-y-2">
        <p class="text-sm text-gray-600">Processing audio input...</p>
        <mat-progress-bar mode="determinate" [value]="progressValue" class="w-full"></mat-progress-bar>
        <p class="text-xs text-gray-500">Analyzing frequency patterns and sound signatures</p>
      </div>
    </mat-card-content>
  </mat-card>

  <!-- Current Detection Results -->
  <mat-card *ngIf="currentDetection" [ngClass]="getThreatColorClass(currentDetection.threat)">
    <mat-card-header>
      <mat-card-title class="flex items-center gap-2">
        <mat-icon class="h-5 w-5" [ngClass]="getThreatTextColorClass(currentDetection.threat)">warning</mat-icon>
        Wildlife Detected!
      </mat-card-title>
    </mat-card-header>
    <mat-card-content class="space-y-4">
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div>
          <label class="text-sm font-medium text-gray-600">Animal</label>
          <p class="text-lg font-semibold">{{ currentDetection.animal }}</p>
        </div>
        <div>
          <label class="text-sm font-medium text-gray-600">Behavior</label>
          <p class="text-lg font-semibold">{{ currentDetection.behavior }}</p>
        </div>
        <div>
          <label class="text-sm font-medium text-gray-600">Confidence</label>
          <p class="text-lg font-semibold">{{ currentDetection.confidence }}%</p>
        </div>
        <div>
          <label class="text-sm font-medium text-gray-600">Location</label>
          <p class="text-lg font-semibold">{{ currentDetection.location }}</p>
        </div>
      </div>

      <div class="flex items-center justify-between">
        <mat-chip-listbox>
          <mat-chip [color]="getBadgeColor(currentDetection.threat)" selected>
            {{ currentDetection.threat }} Threat Level
          </mat-chip>
        </mat-chip-listbox>

        <button *ngIf="currentDetection.threat === 'High' && !alertSent"
          mat-raised-button color="warn" (click)="simulateAlert()">
          Send Emergency Alert
          <mat-icon class="ml-2">message</mat-icon>
        </button>

        <div *ngIf="alertSent" class="flex items-center gap-2 text-green-600">
          <mat-icon class="h-4 w-4">check_circle</mat-icon>
          <span class="text-sm font-medium">Alert Sent Successfully</span>
        </div>
      </div>

      <mat-card *ngIf="currentDetection.threat === 'High'" class="border-red-200 bg-red-50">
        <mat-card-content class="flex items-center gap-2 text-red-800">
          <mat-icon class="h-4 w-4">warning</mat-icon>
          <p><strong>High-Risk Situation Detected!</strong> Aggressive wildlife behavior identified. Immediate action required to prevent human-wildlife conflict.</p>
        </mat-card-content>
      </mat-card>
    </mat-card-content>
  </mat-card>

  <!-- Alert Status -->
  <mat-card *ngIf="alertSent" class="bg-green-50 border-green-200">
    <mat-card-header>
      <mat-card-title class="text-green-800 flex items-center gap-2">
        <mat-icon class="h-5 w-5">check_circle</mat-icon>
        Emergency Alert Dispatched
      </mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 bg-green-500 rounded-full"></div>
          <span>SMS alerts sent to 42 registered travelers</span>
        </div>
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 bg-green-500 rounded-full"></div>
          <span>Email notifications to Forest Rangers</span>
        </div>
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 bg-green-500 rounded-full"></div>
          <span>Patrol units alerted and dispatched</span>
        </div>
      </div>
    </mat-card-content>
  </mat-card>

  <!-- Detection History -->
  <mat-card>
    <mat-card-header>
      <mat-card-title>Recent Detection History</mat-card-title>
      <mat-card-subtitle>Latest wildlife detections from the monitoring system</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      <div class="space-y-3">
        <div *ngFor="let detection of [
          { time: '14:32', animal: 'Tiger', behavior: 'Aggressive', location: 'Sector 7', threat: 'High', alerted: true },
          { time: '14:15', animal: 'Elephant Herd', behavior: 'Crossing', location: 'Highway KM 15', threat: 'Medium', alerted: true },
          { time: '13:58', animal: 'Leopard', behavior: 'Hunting', location: 'Buffer Zone 2', threat: 'High', alerted: true },
          { time: '13:42', animal: 'Peacock', behavior: 'Mating Call', location: 'Trail 1', threat: 'Low', alerted: false },
          { time: '13:28', animal: 'Wild Boar', behavior: 'Feeding', location: 'Water Hole 3', threat: 'Low', alerted: false }
        ]" class="flex items-center justify-between p-3 border rounded-lg">
          <div class="flex items-center gap-4">
            <div class="text-sm font-mono text-gray-500">{{ detection.time }}</div>
            <div>
              <p class="font-medium">{{ detection.animal }}</p>
              <p class="text-sm text-gray-600">{{ detection.location }}</p>
            </div>
            <mat-chip-listbox>
              <mat-chip>{{ detection.behavior }}</mat-chip>
            </mat-chip-listbox>
          </div>
          <div class="flex items-center gap-2">
            <mat-chip-listbox>
              <mat-chip [color]="getBadgeColor(detection.threat)" selected>
                {{ detection.threat }}
              </mat-chip>
            </mat-chip-listbox>
            <mat-icon *ngIf="detection.alerted" class="h-4 w-4 text-green-600">check_circle</mat-icon>
          </div>
        </div>
      </div>
    </mat-card-content>
  </mat-card>
</div>

// components/detection-system.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Radio, AlertTriangle, Phone, Mail, MapPin } from "lucide-react"

export function DetectionSystem() {
  const [isMonitoring, setIsMonitoring] = useState(false)
  const [alerts, setAlerts] = useState<any[]>([])

  const startMonitoring = () => {
    setIsMonitoring(true)

    // Simulate detection after 3 seconds
    setTimeout(() => {
      const newAlert = {
        id: Date.now(),
        animal: "Tiger",
        emotion: "Aggressive",
        location: "Sector 7, Bandipur",
        time: new Date().toLocaleTimeString(),
        threatLevel: "High",
        coordinates: { lat: 11.6854, lng: 76.132 },
      }
      setAlerts((prev) => [newAlert, ...prev])
    }, 3000)
  }

  const stopMonitoring = () => {
    setIsMonitoring(false)
  }

  const sendAlert = (type: "sms" | "email") => {
    // Simulate sending alert
    alert(`${type.toUpperCase()} alert sent to forest rangers and nearby personnel!`)
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Radio className="w-5 h-5" />
            <span>Real-time Detection System</span>
          </CardTitle>
          <CardDescription>Monitor live audio feeds from sensors across Bandipur Reserve</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium">System Status</p>
              <p className="text-sm text-gray-600">{isMonitoring ? "Actively monitoring 24 sensors" : "System idle"}</p>
            </div>
            <div className="flex space-x-2">
              {!isMonitoring ? (
                <Button onClick={startMonitoring} className="bg-green-600 hover:bg-green-700">
                  Start Monitoring
                </Button>
              ) : (
                <Button onClick={stopMonitoring} variant="destructive">
                  Stop Monitoring
                </Button>
              )}
            </div>
          </div>

          {isMonitoring && (
            <div className="bg-green-50 p-4 rounded-lg border border-green-200">
              <div className="flex items-center space-x-2">
                <div className="w-3 h-3 bg-green-500 rounded-full animate-pulse"></div>
                <span className="text-green-800 font-medium">Live Monitoring Active</span>
              </div>
              <p className="text-green-700 text-sm mt-1">Scanning audio patterns from sensors in real-time...</p>
            </div>
          )}
        </CardContent>
      </Card>

      {alerts.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-red-600">Active Alerts</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {alerts.map((alert) => (
              <Alert key={alert.id} className="border-red-200 bg-red-50">
                <AlertTriangle className="h-4 w-4 text-red-600" />
                <AlertDescription>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="font-bold text-red-800">
                        {alert.animal} Detected - {alert.emotion} Behavior
                      </p>
                      <p className="text-red-700">
                        <MapPin className="w-4 h-4 inline mr-1" />
                        {alert.location} at {alert.time}
                      </p>
                      <Badge variant="destructive" className="mt-2">
                        Threat Level: {alert.threatLevel}
                      </Badge>
                    </div>
                    <div className="flex space-x-2">
                      <Button size="sm" variant="outline" onClick={() => sendAlert("sms")}>
                        <Phone className="w-4 h-4 mr-1" />
                        SMS Alert
                      </Button>
                      <Button size="sm" variant="outline" onClick={() => sendAlert("email")}>
                        <Mail className="w-4 h-4 mr-1" />
                        Email Alert
                      </Button>
                    </div>
                  </div>
                </AlertDescription>
              </Alert>
            ))}
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Sensor Network Status</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { sector: "Sector 1", status: "Online", count: 6 },
              { sector: "Sector 2", status: "Online", count: 8 },
              { sector: "Sector 3", status: "Maintenance", count: 4 },
              { sector: "Sector 4", status: "Online", count: 6 },
            ].map((sensor) => (
              <div key={sensor.sector} className="text-center p-3 border rounded-lg">
                <p className="font-medium">{sensor.sector}</p>
                <p className="text-sm text-gray-600">{sensor.count} sensors</p>
                <Badge variant={sensor.status === "Online" ? "default" : "secondary"} className="mt-1">
                  {sensor.status}
                </Badge>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
