// src/app/dashboard/pages/proximity-alerts/proximity-alerts.component.ts
import { Component, type OnInit } from "@angular/core"

@Component({
  selector: "app-proximity-alerts",
  templateUrl: "./proximity-alerts.component.html",
  styleUrls: ["./proximity-alerts.component.css"],
})
export class ProximityAlertsComponent implements OnInit {
  userLocation: { lat: number; lng: number } | null = null
  alerts: any[] = []

  // Simulated animal locations in Bandipur area
  animalLocations = [
    {
      id: 1,
      animal: "Tiger",
      lat: 11.6854,
      lng: 76.5512,
      behavior: "Aggressive",
      lastSeen: "2 min ago",
      distance: 0.8,
    },
    {
      id: 2,
      animal: "Elephant Herd",
      lat: 11.6901,
      lng: 76.5489,
      behavior: "Crossing Road",
      lastSeen: "15 min ago",
      distance: 1.2,
    },
    { id: 3, animal: "Leopard", lat: 11.6823, lng: 76.5534, behavior: "Alert", lastSeen: "45 min ago", distance: 2.1 },
    {
      id: 4,
      animal: "Wild Boar",
      lat: 11.6889,
      lng: 76.5467,
      behavior: "Feeding",
      lastSeen: "1 hour ago",
      distance: 1.8,
    },
    {
      id: 5,
      animal: "Sloth Bear",
      lat: 11.6812,
      lng: 76.5523,
      behavior: "Territorial",
      lastSeen: "2 hours ago",
      distance: 3.2,
    },
  ]

  ngOnInit(): void {
    this.getCurrentLocation()
    this.checkAlerts()
    setInterval(() => this.checkAlerts(), 30000) // Check every 30 seconds
  }

  getCurrentLocation(): void {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          this.userLocation = {
            lat: position.coords.latitude,
            lng: position.coords.longitude,
          }
        },
        () => {
          // Fallback to Bandipur center coordinates
          this.userLocation = { lat: 11.6854, lng: 76.5512 }
        },
      )
    } else {
      this.userLocation = { lat: 11.6854, lng: 76.5512 }
    }
  }

  checkAlerts(): void {
    const highRiskAnimals = this.animalLocations.filter(
      (animal) => animal.distance < 2.0 && (animal.behavior === "Aggressive" || animal.behavior === "Territorial"),
    )
    this.alerts = highRiskAnimals
  }

  sendEmergencyAlert(animal: any): void {
    // Simulate sending SMS/Email alert
    alert(
      `Emergency alert sent to Forest Rangers!\n\nAnimal: ${animal.animal}\nLocation: ${animal.distance}km from your position\nBehavior: ${animal.behavior}`,
    )
  }

  getThreatLevel(distance: number, behavior: string): string {
    if (distance < 1.0 && (behavior === "Aggressive" || behavior === "Territorial")) return "Critical"
    if (distance < 2.0 && behavior === "Aggressive") return "High"
    if (distance < 1.5) return "Medium"
    return "Low"
  }

  getThreatColorClass(level: string): string {
    switch (level) {
      case "Critical":
        return "bg-red-600 text-white"
      case "High":
        return "bg-red-500 text-white"
      case "Medium":
        return "bg-yellow-500 text-white"
      case "Low":
        return "bg-green-500 text-white"
      default:
        return "bg-gray-500 text-white"
    }
  }

  getBadgeColor(level: string): string {
    switch (level) {
      case "Critical":
      case "High":
        return "warn"
      case "Medium":
        return "accent"
      case "Low":
        return "primary"
      default:
        return ""
    }
  }

  getAnimalEmoji(animalName: string): string {
    switch (animalName) {
      case "Tiger":
        return "🐅"
      case "Elephant Herd":
        return "🐘"
      case "Leopard":
        return "🐆"
      case "Wild Boar":
        return "🐗"
      case "Sloth Bear":
        return "🐻"
      default:
        return "🐾"
    }
  }
}

<div class="space-y-6">
  <div>
    <h1 class="text-3xl font-bold text-gray-900">Proximity Alert System</h1>
    <p class="text-gray-600 mt-2">Real-time wildlife proximity monitoring and conflict prevention</p>
  </div>

  <!-- Critical Alerts -->
  <mat-card *ngIf="alerts.length > 0" class="border-red-200 bg-red-50">
    <mat-card-content class="flex items-center gap-2 text-red-800">
      <mat-icon class="h-4 w-4">warning</mat-icon>
      <p><strong>Wildlife Conflict Alert!</strong> {{ alerts.length }} high-risk animal(s) detected within 2km of your location.</p>
    </mat-card-content>
  </mat-card>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <!-- Current Location -->
    <mat-card>
      <mat-card-header>
        <mat-card-title class="flex items-center gap-2">
          <mat-icon class="h-5 w-5">location_on</mat-icon>
          Your Current Location
        </mat-card-title>
        <mat-card-subtitle>GPS coordinates and nearby wildlife activity</mat-card-subtitle>
      </mat-card-header>
      <mat-card-content class="space-y-4">
        <div *ngIf="userLocation">
          <div class="bg-blue-50 p-4 rounded-lg">
            <p class="text-sm text-blue-800 mb-2">
              <strong>Coordinates:</strong> {{ userLocation.lat.toFixed(4) }}, {{ userLocation.lng.toFixed(4) }}
            </p>
            <p class="text-sm text-blue-800">
              <strong>Area:</strong> Bandipur Tiger Reserve - Buffer Zone
            </p>
          </div>

          <button mat-stroked-button (click)="getCurrentLocation()" class="w-full bg-transparent">
            <mat-icon class="h-4 w-4 mr-2">navigation</mat-icon>
            Update Location
          </button>
        </div>
        <div *ngIf="!userLocation" class="text-center py-4">
          <button mat-raised-button color="primary" (click)="getCurrentLocation()">
            <mat-icon class="h-4 w-4 mr-2">location_on</mat-icon>
            Get Current Location
          </button>
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Interactive Map Placeholder -->
    <mat-card>
      <mat-card-header>
        <mat-card-title>Bandipur Reserve Map</mat-card-title>
        <mat-card-subtitle>Wildlife locations and safe zones</mat-card-subtitle>
      </mat-card-header>
      <mat-card-content>
        <div class="bg-green-100 h-64 rounded-lg flex items-center justify-center relative overflow-hidden">
          <div class="absolute inset-0 bg-gradient-to-br from-green-200 to-green-300"></div>
          <div class="relative z-10 text-center">
            <mat-icon class="h-8 w-8 mx-auto mb-2 text-green-700">map</mat-icon>
            <p class="text-green-800 font-medium">Interactive Map</p>
            <p class="text-sm text-green-700">Bandipur Tiger Reserve</p>
          </div>

          <!-- Simulated animal markers -->
          <div class="absolute top-4 left-4 w-3 h-3 bg-red-500 rounded-full animate-pulse"></div>
          <div class="absolute top-12 right-8 w-3 h-3 bg-yellow-500 rounded-full animate-pulse"></div>
          <div class="absolute bottom-8 left-12 w-3 h-3 bg-orange-500 rounded-full animate-pulse"></div>
          <div class="absolute bottom-4 right-4 w-4 h-4 bg-blue-500 rounded-full border-2 border-white"></div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>

  <!-- Nearby Wildlife -->
  <mat-card>
    <mat-card-header>
      <mat-card-title>Nearby Wildlife Activity</mat-card-title>
      <mat-card-subtitle>Animals detected within 5km radius of your location</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      <div class="space-y-4">
        <div *ngFor="let animal of animalLocations" class="flex items-center justify-between p-4 border rounded-lg">
          <div class="flex items-center gap-4">
            <div class="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center">
              <span class="text-2xl">{{ getAnimalEmoji(animal.animal) }}</span>
            </div>
            <div>
              <h4 class="font-semibold">{{ animal.animal }}</h4>
              <p class="text-sm text-gray-600">
                {{ animal.distance }}km away • {{ animal.lastSeen }}
              </p>
              <p class="text-sm">Behavior: {{ animal.behavior }}</p>
            </div>
          </div>
          <div class="text-right space-y-2">
            <mat-chip-listbox>
              <mat-chip [color]="getBadgeColor(getThreatLevel(animal.distance, animal.behavior))" selected>
                {{ getThreatLevel(animal.distance, animal.behavior) }}
              </mat-chip>
            </mat-chip-listbox>
            <div *ngIf="getThreatLevel(animal.distance, animal.behavior) === 'Critical' || getThreatLevel(animal.distance, animal.behavior) === 'High'" class="flex gap-2">
              <button mat-raised-button color="warn" (click)="sendEmergencyAlert(animal)">
                <mat-icon class="h-3 w-3 mr-1">phone</mat-icon>
                Alert
              </button>
            </div>
          </div>
        </div>
      </div>
    </mat-card-content>
  </mat-card>

  <!-- Safety Guidelines -->
  <mat-card class="bg-amber-50 border-amber-200">
    <mat-card-header>
      <mat-card-title class="text-amber-800">Safety Guidelines</mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-amber-800">
        <div>
          <h4 class="font-semibold mb-2">If you encounter wildlife:</h4>
          <ul class="space-y-1 list-disc list-inside">
            <li>Do not run or make sudden movements</li>
            <li>Back away slowly while facing the animal</li>
            <li>Make yourself appear larger</li>
            <li>Do not make direct eye contact</li>
          </ul>
        </div>
        <div>
          <h4 class="font-semibold mb-2">Emergency contacts:</h4>
          <ul class="space-y-1">
            <li>
              <strong>Forest Range Office:</strong> +91-8212-252026
            </li>
            <li>
              <strong>Wildlife Emergency:</strong> +91-9448-123456
            </li>
            <li>
              <strong>Medical Emergency:</strong> 108
            </li>
          </ul>
        </div>
      </div>
    </mat-card-content>
  </mat-card>
</div>

// app/proximity-alerts/page.tsx
"use client"

import { useState, useEffect } from "react"
import { DashboardLayout } from "@/components/dashboard-layout"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { MapPin, AlertTriangle, Navigation, Phone } from "lucide-react"

export default function ProximityAlertsPage() {
  const [userLocation, setUserLocation] = useState<{ lat: number; lng: number } | null>(null)
  const [alerts, setAlerts] = useState<any[]>([])

  // Simulated animal locations in Bandipur area
  const animalLocations = [
    {
      id: 1,
      animal: "Tiger",
      lat: 11.6854,
      lng: 76.5512,
      behavior: "Aggressive",
      lastSeen: "2 min ago",
      distance: 0.8,
    },
    {
      id: 2,
      animal: "Elephant Herd",
      lat: 11.6901,
      lng: 76.5489,
      behavior: "Crossing Road",
      lastSeen: "15 min ago",
      distance: 1.2,
    },
    { id: 3, animal: "Leopard", lat: 11.6823, lng: 76.5534, behavior: "Alert", lastSeen: "45 min ago", distance: 2.1 },
    {
      id: 4,
      animal: "Wild Boar",
      lat: 11.6889,
      lng: 76.5467,
      behavior: "Feeding",
      lastSeen: "1 hour ago",
      distance: 1.8,
    },
    {
      id: 5,
      animal: "Sloth Bear",
      lat: 11.6812,
      lng: 76.5523,
      behavior: "Territorial",
      lastSeen: "2 hours ago",
      distance: 3.2,
    },
  ]

  const getCurrentLocation = () => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setUserLocation({
            lat: position.coords.latitude,
            lng: position.coords.longitude,
          })
        },
        () => {
          // Fallback to Bandipur center coordinates
          setUserLocation({ lat: 11.6854, lng: 76.5512 })
        },
      )
    } else {
      setUserLocation({ lat: 11.6854, lng: 76.5512 })
    }
  }

  useEffect(() => {
    getCurrentLocation()

    // Check for proximity alerts
    const checkAlerts = () => {
      const highRiskAnimals = animalLocations.filter(
        (animal) => animal.distance < 2.0 && (animal.behavior === "Aggressive" || animal.behavior === "Territorial"),
      )
      setAlerts(highRiskAnimals)
    }

    checkAlerts()
    const interval = setInterval(checkAlerts, 30000) // Check every 30 seconds

    return () => clearInterval(interval)
  }, [])

  const sendEmergencyAlert = (animal: any) => {
    // Simulate sending SMS/Email alert
    alert(
      `Emergency alert sent to Forest Rangers!\n\nAnimal: ${animal.animal}\nLocation: ${animal.distance}km from your position\nBehavior: ${animal.behavior}`,
    )
  }

  const getThreatLevel = (distance: number, behavior: string) => {
    if (distance < 1.0 && (behavior === "Aggressive" || behavior === "Territorial")) return "Critical"
    if (distance < 2.0 && behavior === "Aggressive") return "High"
    if (distance < 1.5) return "Medium"
    return "Low"
  }

  const getThreatColor = (level: string) => {
    switch (level) {
      case "Critical":
        return "bg-red-600 text-white"
      case "High":
        return "bg-red-500 text-white"
      case "Medium":
        return "bg-yellow-500 text-white"
      case "Low":
        return "bg-green-500 text-white"
      default:
        return "bg-gray-500 text-white"
    }
  }

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Proximity Alert System</h1>
          <p className="text-gray-600 mt-2">Real-time wildlife proximity monitoring and conflict prevention</p>
        </div>

        {/* Critical Alerts */}
        {alerts.length > 0 && (
          <Alert className="border-red-200 bg-red-50">
            <AlertTriangle className="h-4 w-4 text-red-600" />
            <AlertDescription className="text-red-800">
              <strong>Wildlife Conflict Alert!</strong> {alerts.length} high-risk animal(s) detected within 2km of your
              location.
            </AlertDescription>
          </Alert>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Current Location */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <MapPin className="h-5 w-5" />
                Your Current Location
              </CardTitle>
              <CardDescription>GPS coordinates and nearby wildlife activity</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {userLocation ? (
                <div>
                  <div className="bg-blue-50 p-4 rounded-lg">
                    <p className="text-sm text-blue-800 mb-2">
                      <strong>Coordinates:</strong> {userLocation.lat.toFixed(4)}, {userLocation.lng.toFixed(4)}
                    </p>
                    <p className="text-sm text-blue-800">
                      <strong>Area:</strong> Bandipur Tiger Reserve - Buffer Zone
                    </p>
                  </div>

                  <Button onClick={getCurrentLocation} variant="outline" className="w-full bg-transparent">
                    <Navigation className="h-4 w-4 mr-2" />
                    Update Location
                  </Button>
                </div>
              ) : (
                <div className="text-center py-4">
                  <Button onClick={getCurrentLocation}>
                    <MapPin className="h-4 w-4 mr-2" />
                    Get Current Location
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Interactive Map Placeholder */}
          <Card>
            <CardHeader>
              <CardTitle>Bandipur Reserve Map</CardTitle>
              <CardDescription>Wildlife locations and safe zones</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="bg-green-100 h-64 rounded-lg flex items-center justify-center relative overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-br from-green-200 to-green-300"></div>
                <div className="relative z-10 text-center">
                  <MapPin className="h-8 w-8 mx-auto mb-2 text-green-700" />
                  <p className="text-green-800 font-medium">Interactive Map</p>
                  <p className="text-sm text-green-700">Bandipur Tiger Reserve</p>
                </div>

                {/* Simulated animal markers */}
                <div className="absolute top-4 left-4 w-3 h-3 bg-red-500 rounded-full animate-pulse"></div>
                <div className="absolute top-12 right-8 w-3 h-3 bg-yellow-500 rounded-full animate-pulse"></div>
                <div className="absolute bottom-8 left-12 w-3 h-3 bg-orange-500 rounded-full animate-pulse"></div>
                <div className="absolute bottom-4 right-4 w-4 h-4 bg-blue-500 rounded-full border-2 border-white"></div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Nearby Wildlife */}
        <Card>
          <CardHeader>
            <CardTitle>Nearby Wildlife Activity</CardTitle>
            <CardDescription>Animals detected within 5km radius of your location</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {animalLocations.map((animal) => {
                const threatLevel = getThreatLevel(animal.distance, animal.behavior)
                return (
                  <div key={animal.id} className="flex items-center justify-between p-4 border rounded-lg">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center">
                        <span className="text-2xl">
                          {animal.animal === "Tiger"
                            ? "🐅"
                            : animal.animal === "Elephant Herd"
                              ? "🐘"
                              : animal.animal === "Leopard"
                                ? "🐆"
                                : animal.animal === "Wild Boar"
                                  ? "🐗"
                                  : "🐻"}
                        </span>
                      </div>
                      <div>
                        <h4 className="font-semibold">{animal.animal}</h4>
                        <p className="text-sm text-gray-600">
                          {animal.distance}km away • {animal.lastSeen}
                        </p>
                        <p className="text-sm">Behavior: {animal.behavior}</p>
                      </div>
                    </div>
                    <div className="text-right space-y-2">
                      <Badge className={getThreatColor(threatLevel)}>{threatLevel}</Badge>
                      {(threatLevel === "Critical" || threatLevel === "High") && (
                        <div className="flex gap-2">
                          <Button size="sm" variant="destructive" onClick={() => sendEmergencyAlert(animal)}>
                            <Phone className="h-3 w-3 mr-1" />
                            Alert
                          </Button>
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </CardContent>
        </Card>

        {/* Safety Guidelines */}
        <Card className="bg-amber-50 border-amber-200">
          <CardHeader>
            <CardTitle className="text-amber-800">Safety Guidelines</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-amber-800">
              <div>
                <h4 className="font-semibold mb-2">If you encounter wildlife:</h4>
                <ul className="space-y-1 list-disc list-inside">
                  <li>Do not run or make sudden movements</li>
                  <li>Back away slowly while facing the animal</li>
                  <li>Make yourself appear larger</li>
                  <li>Do not make direct eye contact</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Emergency contacts:</h4>
                <ul className="space-y-1">
                  <li>
                    <strong>Forest Range Office:</strong> +91-8212-252026
                  </li>
                  <li>
                    <strong>Wildlife Emergency:</strong> +91-9448-123456
                  </li>
                  <li>
                    <strong>Medical Emergency:</strong> 108
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  )
}
